name: idonate
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1
  table_calendar: ^3.0.9
  intl: ^0.19.0
  timeago: ^3.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  google_sign_in: ^6.1.6
  firebase_messaging: ^14.7.9
  http: ^1.1.2
  js: ^0.7.2
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

  assets:
    - assets/images/
    - assets/images/blood.png
    - assets/images/free.png
    - assets/images/google.png
    - assets/images/blood_donation.jpg
    - assets/images/connecting.jpg
    - assets/images/privacy.jpg
    - assets/images/fast.jpg
    - assets/fonts/
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Bold.ttf
    - assets/fonts/Montserrat-Italic.ttf