// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfBd20E5_D-RPTbDE2G0LKDOVhnBRd8M',
    appId: '1:655086831488:web:9cf7266977cc7e1ca9e365',
    messagingSenderId: '655086831488',
    projectId: 'idonate-c030e',
    authDomain: 'idonate-c030e.firebaseapp.com',
    storageBucket: 'idonate-c030e.firebasestorage.app',
    measurementId: 'G-TJNSXXT69F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaangDOqoYGZ9YlZ-7IE0TO3vGFAWddZw',
    appId: '1:655086831488:android:fb0e473c117e2890a9e365',
    messagingSenderId: '655086831488',
    projectId: 'idonate-c030e',
    storageBucket: 'idonate-c030e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6rtyKsI6ANtopTa-qw4s8n-d_rxSDhQ',
    appId: '1:655086831488:ios:f2a4c854c16da554a9e365',
    messagingSenderId: '655086831488',
    projectId: 'idonate-c030e',
    storageBucket: 'idonate-c030e.firebasestoragey.app',
    iosBundleId: 'com.example.idonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl6rtyKsI6ANtopTa-qw4s8n-d_rxSDhQ',
    appId: '1:655086831488:ios:f2a4c854c16da554a9e365',
    messagingSenderId: '655086831488',
    projectId: 'idonate-c030e',
    storageBucket: 'idonate-c030e.firebasestorage.app',
    iosBundleId: 'com.example.idonate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnfBd20E5_D-RPTbDE2G0LKDOVhnBRd8M',
    appId: '1:655086831488:web:73f05c6f7bb66871a9e365',
    messagingSenderId: '655086831488',
    projectId: 'idonate-c030e',
    authDomain: 'idonate-c030e.firebaseapp.com',
    storageBucket: 'idonate-c030e.firebasestorage.app',
    measurementId: 'G-GNH0BSWGXY',
  );
}
